services:
  discord:
    build: ./discord
    environment:
        - WEB_SCRAPER_PROTOCOL=${WEB_SCRAPER_PROTOCOL}
        - WEB_SCRAPER_HOSTNAME=${WEB_SCRAPER_HOSTNAME}
        - WEB_SCRAPER_PORT=${WEB_SCRAPER_PORT}
  web-scraper:
    build: ./web-scraper
    ports:
      - "${WEB_SCRAPER_PORT}:${WEB_SCRAPER_PORT}"
    environment:
      - WEB_SCRAPER_HOSTNAME=${WEB_SCRAPER_HOSTNAME}
      - WEB_SCRAPER_PORT=${WEB_SCRAPER_PORT}